### ISSUE TITLE
Check when migration is empty

### ISSUE THREAD

**Issue by raigons** [betrybe/neo4_ecto#16]
For now is still possible to run empty migrations, with no content on functions up and down and the migration is saved on `SCHEMA_MIGRATION`.   

Runner (or Migrator) should avoid running empty migrations and raise an error 

cc @Caciquez

**Comment by norbajunior** [comment]
@raigons @Caciquez as far as I know the default behaviour when we run migrations is not raise an error and it does save into schema_migrations even empty 🤔 or am I missing something?

**Comment by Caciquez** [comment]
> @raigons @Caciquez as far as I know the default behaviour when we run migrations is not raise an error and it does save into schema_migrations even empty 🤔 or am I missing something?

Nice point @norbajunior i guess it's a default behaviour to run migrations even if they are `empty`.

I will be closing this issue then
